// USER logics

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const SEND_RESET_PASSWORD = 'SEND_RESET_PASSWORD';
export const CONNECTION_REQUEST = 'CONNECTION_REQUEST';


export const GET_REFERRAL_CODE_REQUEST = 'GET_REFERRAL_CODE_REQUEST';
export const GET_REFERRAL_CODE_SUCCESS = 'GET_REFERRAL_CODE_SUCCESS';
export const GET_REFERRAL_CODE_FAILURE = 'GET_REFERRAL_CODE_FAILURE';


export const VALIDATE_REFERRAL_CODE_REQUEST = 'VALIDATE_REFERRAL_CODE_REQUEST';
export const VALIDATE_REFERRAL_CODE_SUCCESS = 'VALIDATE_REFERRAL_CODE_SUCCESS';
export const VALIDATE_REFERRAL_CODE_FAILURE = 'VALIDATE_REFERRAL_CODE_FAILURE';


export const DELETE_USER = 'DELETE_USER';
export const SEND_POINTS_REQUEST = 'SEND_POINTS_REQUEST';
export const SEND_POINTS_SUCCESS = 'SEND_POINTS_SUCCESS';
export const SEND_POINTS_FAILURE = 'SEND_POINTS_FAILURE';

export const REQUEST_PAYMENT_REQUEST = 'SEND_POINTS_REQUEST';
export const REQUEST_PAYMENT_SUCCESS = 'SEND_POINTS_SUCCESS';
export const REQUEST_PAYMENT_FAILURE = 'SEND_POINTS_FAILURE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const  BUY_AIRTIME_REQUEST = 'BUY_AIRTIME';
export const  BUY_AIRTIME_SUCCESS = 'BUY_AIRTIME_SUCCESS';
export const  BUY_AIRTIME_FAILURE = 'BUY_AIRTIME_FAILURE';

export const FETCH_WASTE_REQUEST = 'FETCH_WASTE_REQUEST';
export const FETCH_WASTE_SUCCESS = 'FETCH_WASTE_SUCCESS';
export const FETCH_WASTE_FAILURE = 'FETCH_WASTE_FAILURE';
// SQUADS EXPO 
export const CREATE_SQUAD_REQUEST = 'CREATE_SQUAD_REQUEST';
export const CREATE_SQUAD_SUCCESS = 'CREATE_SQUAD_SUCCESS';
export const CREATE_SQUAD_FAILURE = 'CREATE_SQUAD_FAILURE';
export const JOIN_SQUAD_REQUEST = 'REQUEST_JOIN';
export const REQUEST_JOIN_SQUAD_SUCCESS = 'JOIN_SUCCESS';
export const REQUEST_JOIN_SQUAD_FAILURE = 'JOIN_FAILURE';
export const APPROVE_JOIN_REQUEST_REQUEST = 'APPROVE_JOIN_REQUEST';
export const APPROVE_JOIN_REQUEST_SUCCESS = 'APPROVE_JOIN_REQUEST_SUCCESS';
export const APPROVE_JOIN_REQUEST_FAILURE = 'APPROVE_JOIN_REQUEST_FAILURE';
export const REMOVE_MEMBER_REQUEST = 'REMOVE_MEMBER_REQUEST';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';
export const REMOVE_MEMBER_FAILURE = 'REMOVE_MEMBER_FAILURE';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILURE = 'ADD_MEMBER_FAILURE';
export const LEAVE_SQUAD_REQUEST = 'LEAVE_SQUAD_REQUEST';
export const LEAVE_SQUAD_SUCCESS = 'LEAVE_SQUAD_SUCCESS';
export const LEAVE_SQUAD_FAILURE = 'LEAVE_SQUAD_FAILURE';
export const DELETE_SQUAD_REQUEST = 'DELETE_SQUAD_REQUEST';
export const DELETE_SQUAD_SUCCESS = 'DELETE_SQUAD_SUCCESS';
export const DELETE_SQUAD_FAILURE = 'DELETE_SQUAD_FAILURE';
export const GET_ALL_SQUADS_REQUEST = 'GET_ALL_SQUADS_REQUEST';
export const GET_ALL_SQUADS_SUCCESS = 'GET_ALL_SQUADS_SUCCESS';
export const GET_ALL_SQUADS_FAILURE = 'GET_ALL_SQUADS_FAILURE';
export const UPDATE_SQUAD_REQUEST = 'UPDATE_SQUAD_REQUEST';
export const UPDATE_SQUAD_SUCCESS = 'UPDATE_SQUAD_SUCCESS';
export const UPDATE_SQUAD_FAILURE = 'UPDATE_SQUAD_FAILURE';
export const SUBMIT_ACTIVE_REQUEST = 'SUBMIT_ACTIVE_REQUEST';
export const SUBMIT_ACTIVE_SUCCESS = 'SUBMIT_ACTIVE_SUCCESS';
export const SUBMIT_ACTIVE_FAILURE = 'SUBMIT_ACTIVE_FAILURE';
export const FETCH_SQUAD_DATA_REQUEST = 'FETCH_SQUAD_DATA_REQUEST';
export const FETCH_SQUAD_DATA_SUCCESS = 'FETCH_SQUAD_DATA_SUCCESS';
export const FETCH_SQUAD_DATA_FAILURE = 'FETCH_SQUAD_DATA_FAILURE';


// POSTS

// src/redux/actions/actionTypes.js
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const SHARE_POST_REQUEST = 'SHARE_POST_REQUEST';
export const SHARE_POST_SUCCESS = 'SHARE_POST_SUCCESS';
export const SHARE_POST_FAILURE = 'SHARE_POST_FAILURE';

export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POSTS_FAILURE';

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_FAILURE = 'GET_POST_BY_ID_FAILURE';

export const VIEW_SHARED_POST_REQUEST = 'VIEW_SHARED_POST_REQUEST';
export const VIEW_SHARED_POST_SUCCESS = 'VIEW_SHARED_POST_SUCCESS';
export const VIEW_SHARED_POST_FAILURE = 'VIEW_SHARED_POST_FAILURE';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const GET_ALL_COMMENTS_REQUEST = 'GET_ALL_COMMENTS_REQUEST';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAILURE = 'GET_ALL_COMMENTS_FAILURE';

export const BOOKMARK_POST_REQUEST = 'BOOKMARK_POST_REQUEST';
export const  BOOKMARK_POST_SUCCESS = 'BOOKMARK_POST_SUCCESS';
export const  BOOKMARK_POST_FAILURE = 'BOOKMARK_POST_FAILURE';


export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

export const FETCH_TRENDING_TAGS_REQUEST = 'FETCH_TRENDING_TAGS_REQUEST';
export const FETCH_TRENDING_TAGS_SUCCESS = 'FETCH_TRENDING_TAGS_SUCCESS';
export const FETCH_TRENDING_TAGS_FAILURE = 'FETCH_TRENDING_TAGS_FAILURE';

export const FETCH_POPULAR_TAGS_REQUEST = 'FETCH_POPULAR_TAGS_REQUEST';
export const FETCH_POPULAR_TAGS_SUCCESS = 'FETCH_POPULAR_TAGS_SUCCESS';
export const FETCH_POPULAR_TAGS_FAILURE = 'FETCH_POPULAR_TAGS_FAILURE';

// LEADERBOARDS

export const FETCH_SQUAD_LEADERBOARD_REQUEST = 'FETCH_SQUAD_LEADERBOARD_REQUEST';
export const FETCH_SQUAD_LEADERBOARD_SUCCESS = 'FETCH_SQUAD_LEADERBOARD_SUCCESS';
export const FETCH_SQUAD_LEADERBOARD_FAILURE = 'FETCH_SQUAD_LEADERBOARD_FAILURE';

export const FETCH_USER_LEADERBOARD_REQUEST = 'FETCH_USER_LEADERBOARD_REQUEST';
export const FETCH_USER_LEADERBOARD_SUCCESS = 'FETCH_USER_LEADERBOARD_SUCCESS';
export const FETCH_USER_LEADERBOARD_FAILURE = 'FETCH_USER_LEADERBOARD_FAILURE';


// src/redux/actions/actionTypes.js
export const FETCH_ADMINS_REQUEST = 'FETCH_ADMINS_REQUEST';
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS';
export const FETCH_ADMINS_FAILURE = 'FETCH_ADMINS_FAILURE';

export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_FAILURE = 'ADD_ADMIN_FAILURE';

export const DELETE_ADMIN_REQUEST = 'DELETE_ADMIN_REQUEST';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAILURE = 'DELETE_ADMIN_FAILURE';

export const UPDATE_ADMIN_CREDENTIALS_REQUEST = 'UPDATE_ADMIN_CREDENTIALS_REQUEST';
export const UPDATE_ADMIN_CREDENTIALS_SUCCESS = 'UPDATE_ADMIN_CREDENTIALS_SUCCESS';
export const UPDATE_ADMIN_CREDENTIALS_FAILURE = 'UPDATE_ADMIN_CREDENTIALS_FAILURE';

export const UPDATE_ADMIN_PASSWORD_REQUEST = 'UPDATE_ADMIN_PASSWORD_REQUEST';
export const UPDATE_ADMIN_PASSWORD_SUCCESS = 'UPDATE_ADMIN_PASSWORD_SUCCESS';
export const UPDATE_ADMIN_PASSWORD_FAILURE = 'UPDATE_ADMIN_PASSWORD_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';


export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const PURCHASE_PRODUCT_REQUEST = 'PURCHASE_PRODUCT_REQUEST';
export const PURCHASE_PRODUCT_SUCCESS = 'PURCHASE_PRODUCT_SUCCESS';
export const PURCHASE_PRODUCT_FAILURE = 'PURCHASE_PRODUCT_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const DECREASE_QUANTITY_ERROR = 'DECREASE_QUANTITY_ERROR';
export const ADD_QUANTITY_ERROR = 'ADD_QUANTITY_ERROR';


export const SUBSCRIBE_PRODUCT_REQUEST = 'SUBSCRIBE_PRODUCT_REQUEST';
export const SUBSCRIBE_PRODUCT_SUCCESS = 'SUBSCRIBE_PRODUCT_SUCCESS';
export const SUBSCRIBE_PRODUCT_FAILURE = 'SUBSCRIBE_PRODUCT_FAILURE';

export const CANCEL_SUBSCRIPTION_REQUEST = 'CANCEL_SUBSCRIPTION_REQUEST';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = 'CANCEL_SUBSCRIPTION_FAILURE';


// MESSAGE SPECIFIC
export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE';

export const UPDATE_MESSAGE_STATUS_REQUEST = 'UPDATE_MESSAGE_STATUS_REQUEST';
export const UPDATE_MESSAGE_STATUS_SUCCESS = 'UPDATE_MESSAGE_STATUS_SUCCESS';
export const UPDATE_MESSAGE_STATUS_FAILURE = 'UPDATE_MESSAGE_STATUS_FAILURE';

// Retaining chat-specific actions
export const FETCH_CHATS_REQUEST = 'FETCH_CHATS_REQUEST';
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILURE = 'DELETE_CHAT_FAILURE';

export const UPDATE_CHAT_STATUS_REQUEST = 'UPDATE_CHAT_STATUS_REQUEST';
export const UPDATE_CHAT_STATUS_SUCCESS = 'UPDATE_CHAT_STATUS_SUCCESS';
export const UPDATE_CHAT_STATUS_FAILURE = 'UPDATE_CHAT_STATUS_FAILURE';

export const SET_ONLINE_STATUS_REQUEST = 'SET_ONLINE_STATUS_REQUEST';
export const SET_ONLINE_STATUS_SUCCESS = 'SET_ONLINE_STATUS_SUCCESS';
export const SET_ONLINE_STATUS_FAILURE= 'SET_ONLINE_STATUS_FAILURE';

export const SRECEIVE_MESSAGE= 'RECEIVE_MESSAGE';
export const ATTACH_FILE_REQUEST= 'ATTACH_FILE_REQUEST';
export const ATTACH_FILE_SUCCESS= 'ATTACH_FILE_SUCCESS,';
export const ATTACH_FILE_FAILURE= 'ATTACH_FILE_FAILURE';


// PAYMENTS

export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST';
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS';
export const DEPOSIT_FAILURE = 'DEPOSIT_FAILURE';

export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAILURE = 'WITHDRAW_FAILURE';

//  SHOPS

// src/redux/actions/actionTypes.js
export const CREATE_SHOP_REQUEST = 'CREATE_SHOP_REQUEST';
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS';
export const CREATE_SHOP_FAILURE = 'CREATE_SHOP_FAILURE';

export const UPDATE_SHOP_REQUEST = 'UPDATE_SHOP_REQUEST';
export const UPDATE_SHOP_SUCCESS = 'UPDATE_SHOP_SUCCESS';
export const UPDATE_SHOP_FAILURE = 'UPDATE_SHOP_FAILURE';

export const DELETE_SHOP_REQUEST = 'DELETE_SHOP_REQUEST';
export const DELETE_SHOP_SUCCESS = 'DELETE_SHOP_SUCCESS';
export const DELETE_SHOP_FAILURE = 'DELETE_SHOP_FAILURE';

export const GET_NEARBY_SHOPS_REQUEST = 'GET_NEARBY_SHOPS_REQUEST';
export const GET_NEARBY_SHOPS_SUCCESS = 'GET_NEARBY_SHOPS_SUCCESS';
export const GET_NEARBY_SHOPS_FAILURE = 'GET_NEARBY_SHOPS_FAILURE';

export const GET_SHOP_BY_ID_REQUEST = 'GET_SHOP_BY_ID_REQUEST';
export const GET_SHOP_BY_ID_SUCCESS = 'GET_SHOP_BY_ID_SUCCESS';
export const GET_SHOP_BY_ID_FAILURE = 'GET_SHOP_BY_ID_FAILURE';

// REPORTS
export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAILURE = 'CREATE_REPORT_FAILURE';

export const GET_ALL_REPORTS_REQUEST = 'GET_ALL_REPORTS_REQUEST';
export const GET_ALL_REPORTS_SUCCESS = 'GET_ALL_REPORTS_SUCCESS';
export const GET_ALL_REPORTS_FAILURE = 'GET_ALL_REPORTS_FAILURE';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAILURE = 'DELETE_REPORT_FAILURE';

// DONATIONS
// src/redux/actions/actionTypes.js
export const CREATE_DONATION_REQUEST = 'CREATE_DONATION_REQUEST';
export const CREATE_DONATION_SUCCESS = 'CREATE_DONATION_SUCCESS';
export const CREATE_DONATION_FAILURE = 'CREATE_DONATION_FAILURE';

export const GET_ALL_DONATIONS_REQUEST = 'GET_ALL_DONATIONS_REQUEST';
export const GET_ALL_DONATIONS_SUCCESS = 'GET_ALL_DONATIONS_SUCCESS';
export const GET_ALL_DONATIONS_FAILURE = 'GET_ALL_DONATIONS_FAILURE';

export const UPDATE_DONATION_REQUEST = 'UPDATE_DONATION_REQUEST';
export const UPDATE_DONATION_SUCCESS = 'UPDATE_DONATION_SUCCESS';
export const UPDATE_DONATION_FAILURE = 'UPDATE_DONATION_FAILURE';

export const DELETE_DONATION_REQUEST = 'DELETE_DONATION_REQUEST';
export const DELETE_DONATION_SUCCESS = 'DELETE_DONATION_SUCCESS';
export const DELETE_DONATION_FAILURE = 'DELETE_DONATION_FAILURE';

export const CLEAR_ALL_DONATIONS_REQUEST = 'CLEAR_ALL_DONATIONS_REQUEST';
export const CLEAR_ALL_DONATIONS_SUCCESS = 'CLEAR_ALL_DONATIONS_SUCCESS';
export const CLEAR_ALL_DONATIONS_FAILURE = 'CLEAR_ALL_DONATIONS_FAILURE';


export const CREATE_VENDOR_REQUEST = 'CREATE_VENDOR_REQUEST';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_FAILURE = 'CREATE_VENDOR_FAILURE';

export const GET_ALL_VENDORS_REQUEST = 'GET_ALL_VENDORS_REQUEST';
export const GET_ALL_VENDORS_SUCCESS = 'GET_ALL_VENDORS_SUCCESS';
export const GET_ALL_VENDORS_FAILURE = 'GET_ALL_VENDORS_FAILURE';
export const  FETCH_FOLLOWED_VENDORS_SUCCESS = 'FETCH_FOLLOWED_VENDORS_SUCCESS'

export const DELETE_VENDOR_REQUEST = 'DELETE_VENDOR_REQUEST';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAILURE = 'DELETE_VENDOR_FAILURE';

export const UNFOLLOW_VENDOR_REQUEST = 'UNFOLLOW_VENDOR_REQUEST';
export const UNFOLLOW_VENDOR_SUCCESS = 'UNFOLLOW_VENDOR_SUCCESS';
export const UNFOLLOW_VENDOR_FAILURE = 'UNFOLLOW_VENDOR_FAILURE';

// Product Rating Action Types
export const RATE_PRODUCT = 'RATE_PRODUCT';
export const RATE_PRODUCT_SUCCESS = 'RATE_PRODUCT_SUCCESS';
export const RATE_PRODUCT_FAILURE = 'RATE_PRODUCT_FAILURE';

// Vendor Rating Action Types
export const RATE_VENDOR = 'RATE_VENDOR';
export const RATE_VENDOR_SUCCESS = 'RATE_VENDOR_SUCCESS';
export const RATE_VENDOR_FAILURE = 'RATE_VENDOR_FAILURE';

// App Rating Action Types
export const RATE_APP = 'RATE_APP';
export const RATE_APP_SUCCESS = 'RATE_APP_SUCCESS';
export const RATE_APP_FAILURE = 'RATE_APP_FAILURE';

// Fetch Product Ratings Action Types
export const FETCH_PRODUCT_RATINGS_REQUEST = 'FETCH_PRODUCT_RATINGS_REQUEST';
export const FETCH_PRODUCT_RATINGS_SUCCESS = 'FETCH_PRODUCT_RATINGS_SUCCESS';
export const FETCH_PRODUCT_RATINGS_FAILURE = 'FETCH_PRODUCT_RATINGS_FAILURE';

// Fetch Vendor Ratings Action Types
export const FETCH_VENDOR_RATINGS_REQUEST = 'FETCH_VENDOR_RATINGS_REQUEST';
export const FETCH_VENDOR_RATINGS_SUCCESS = 'FETCH_VENDOR_RATINGS_SUCCESS';
export const FETCH_VENDOR_RATINGS_FAILURE = 'FETCH_VENDOR_RATINGS_FAILURE';

// Fetch App Ratings Action Types
export const FETCH_APP_RATINGS_REQUEST = 'FETCH_APP_RATINGS_REQUEST';
export const FETCH_APP_RATINGS_SUCCESS = 'FETCH_APP_RATINGS_SUCCESS';
export const FETCH_APP_RATINGS_FAILURE = 'FETCH_APP_RATINGS_FAILURE';

export const FETCH_BALANCE_REQUEST = 'FETCH_BALANCE_REQUEST';
export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS';
export const FETCH_BALANCE_FAILURE = 'FETCH_BALANCE_FAILURE';

export const FETCH_TOKEN_BALANCE_REQUEST = 'FETCH_TOKEN_BALANCE_REQUEST';
export const FETCH_TOKEN_BALANCE_SUCCESS = 'FETCH_TOKEN_BALANCE_SUCCESS';
export const FETCH_TOKEN_BALANCE_FAILURE = 'FETCH_TOKEN_BALANCE_FAILURE';

export const ACCEPT_CODE = 'ACCEPT_CODE';
export const ACCEPT_CODE_SUCCESS = 'ACCEPT_CODE_SUCCESS';
export const ACCEPT_CODE_FAILURE = 'ACCEPT_CODE_FAILURE';

export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const MARK_AS_READ = 'MARK_AS_READ';

// Create Purchase
export const CREATE_PURCHASE_REQUEST = "CREATE_PURCHASE_REQUEST";
export const CREATE_PURCHASE_SUCCESS = "CREATE_PURCHASE_SUCCESS";
export const CREATE_PURCHASE_FAILURE = "CREATE_PURCHASE_FAILURE";

// Get All Purchases
export const GET_ALL_PURCHASES_REQUEST = "GET_ALL_PURCHASES_REQUEST";
export const GET_ALL_PURCHASES_SUCCESS = "GET_ALL_PURCHASES_SUCCESS";
export const GET_ALL_PURCHASES_FAILURE = "GET_ALL_PURCHASES_FAILURE";

// Update Purchase
export const UPDATE_PURCHASE_REQUEST = "UPDATE_PURCHASE_REQUEST";
export const UPDATE_PURCHASE_SUCCESS = "UPDATE_PURCHASE_SUCCESS";
export const UPDATE_PURCHASE_FAILURE = "UPDATE_PURCHASE_FAILURE";

// Delete Purchase
export const DELETE_PURCHASE_REQUEST = "DELETE_PURCHASE_REQUEST";
export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS";
export const DELETE_PURCHASE_FAILURE = "DELETE_PURCHASE_FAILURE";

// Clear All Purchases
export const CLEAR_ALL_PURCHASES_REQUEST = "CLEAR_ALL_PURCHASES_REQUEST";
export const CLEAR_ALL_PURCHASES_SUCCESS = "CLEAR_ALL_PURCHASES_SUCCESS";
export const CLEAR_ALL_PURCHASES_FAILURE = "CLEAR_ALL_PURCHASES_FAILURE";


export const INITIATE_CALL_REQUEST = 'INITIATE_CALL_REQUEST';
export const INITIATE_CALL_SUCCESS = 'INITIATE_CALL_SUCCESS';
export const INITIATE_CALL_FAILURE = 'INITIATE_CALL_FAILURE';
export const END_CALL_REQUEST = 'END_CALL_REQUEST';
export const END_CALL_SUCCESS = 'END_CALL_SUCCESS';
export const END_CALL_FAILURE = 'END_CALL_FAILURE';

export const FETCH_PURCHASE_TIERS = 'FETCH_PURCHASE_TIERS';
export const FETCH_PURCHASE_TIERS_SUCCESS = 'FETCH_PURCHASE_TIERS_SUCCESS';
export const FETCH_PURCHASE_TIERS_FAILURE = 'FETCH_PURCHASE_TIERS_FAILURE';

export const FETCH_DONATION_TIERS = 'FETCH_DONATION_TIERS';
export const FETCH_DONATION_TIERS_SUCCESS = 'FETCH_DONATION_TIERS_SUCCESS';
export const FETCH_DONATION_TIERS_FAILURE = 'FETCH_DONATION_TIERS_FAILURE';

export const FETCH_COINS = 'FETCH_COINS';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_FAILURE = 'FETCH_COINS_FAILURE';

export const FETCH_TIERS = 'FETCH_TIERS';
export const FETCH_TIERS_SUCCESS = 'FETCH_TIERS_SUCCESS';
export const FETCH_TIERS_FAILURE = 'FETCH_TIERS_FAILURE';

export const FETCH_COUPON_GIFTS = 'FETCH_COUPON_GIFTS';
export const FETCH_COUPON_GIFTS_SUCCESS = 'FETCH_COUPON_GIFTS_SUCCESS';
export const FETCH_COUPON_GIFTS_FAILURE = 'FETCH_COUPON_GIFTS_FAILURE';

export const FETCH_GREEN_CARBON_POINTS = 'FETCH_GREEN_CARBON_POINTS';
export const FETCH_GREEN_CARBON_POINTS_SUCCESS = 'FETCH_GREEN_CARBON_POINTS_SUCCESS';
export const FETCH_GREEN_CARBON_POINTS_FAILURE = 'FETCH_GREEN_CARBON_POINTS_FAILURE';

export const FETCH_VOUCHERS = 'FETCH_VOUCHERS';
export const FETCH_VOUCHERS_SUCCESS = 'FETCH_VOUCHERS_SUCCESS';
export const FETCH_VOUCHERS_FAILURE = 'FETCH_VOUCHERS_FAILURE';

export const FETCH_GREEN_GIFTS = 'FETCH_GREEN_GIFTS';
export const FETCH_GREEN_GIFTS_SUCCESS = 'FETCH_GREEN_GIFTS_SUCCESS';
export const FETCH_GREEN_GIFTS_FAILURE = 'FETCH_GREEN_GIFTS_FAILURE';

export const UPDATE_COINS = 'UPDATE_COINS';
